Create variable-template.yaml
virtual-maker-net/Buildalon pull request #3
Opened 2024-07-25 15:19 UTC by nicholas-hoy-champain

To be used by the self-service workflow

2024-07-25 15:23 UTC, afarchy commented on workflows/variable-template.yaml
> +      #INCLUDEPROLINES#max-parallel: 2 # Use this if you're activating pro license with matrix
I don't think this will help if I have multiple projects to build

2024-07-25 15:24 UTC, afarchy commented on workflows/variable-template.yaml
> +  workflow_dispatch:
I think the template should include a clean flag

2024-07-25 15:25 UTC, afarchy commented on workflows/variable-template.yaml
> +        uses: xrtk/unity-build@v6
personally I like unity-action over unity build

2024-07-25 15:26 UTC, afarchy commented on workflows/variable-template.yaml
> +# Initially created using the Buildalon Action Builder
are we missing step to upload artifacts?

2024-07-25 15:29 UTC, StephenHodgson commented on workflows/variable-template.yaml
> +        uses: xrtk/unity-build@v6
agreed. gives more fine grained control

2024-07-25 15:31 UTC, afarchy commented on workflows/variable-template.yaml
> +      #INCLUDEEDITORUNITTESTS#- uses: xrtk/unity-action@v6
INCLUDE_EDITOR_UNIT_TESTS

2024-07-25 18:16 UTC, StephenHodgson commented on workflows/variable-template.yaml
> +            !${{ env.UNITY_PROJECT_PATH }}/Builds/${{ matrix.build-target }}/*_BurstDebugInformation_DoNotShip/**
we should prob make this configurable too. It'll heavily change dep on the build target, platforms, and expected executables

2024-07-25 19:42 UTC, afarchy commented on workflows/variable-template.yaml
> +          #INCLUDE_PRO_LINES#serial: ${{ secrets.UNITY_SERIAL }} # Used for pro license activations
I believe this line can be here in both cases, it just won't do anything for personal

2024-07-26 01:13 UTC, nicholas-hoy-champain commented on workflows/variable-template.yaml
> +          #INCLUDE_PRO_LINES#serial: ${{ secrets.UNITY_SERIAL }} # Used for pro license activations
We comment it out in case they're using personal. Our intent is to build our docs out so users can learn how to read/write these workflows themselves. I think although it might not break the workflow, it could confuse the users if we have it in there (or worse, teach them the wrong thing).

2024-07-26 01:39 UTC, StephenHodgson commented on workflows/variable-template.yaml
> +          clean: ${{ github.event.inputs.clean }}
```suggestion
          clean: ${{ github.event.inputs.clean == 'true' }}
```

2024-07-26 01:39 UTC, StephenHodgson requested changes
see comment

2024-07-26 01:59 UTC, StephenHodgson approved these changes

2024-07-26 01:59 UTC, merged